spring:
  redis:
    database: 0
    host: 192.168.0.100
    port: 7379
    timeout: 3000ms
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: 2000
        max-wait: 1000ms
    password: weidian2016